/**
 * Stable, documented diagnostic codes. These strings are part of the public
 * contract: CI consumers may match on them and must not need to parse human
 * message wording. See docs/specification/diagnostics.md for the full
 * reference, including remediation guidance for each code.
 */
export const DIAGNOSTIC_CODES = [
  "CONTRACT_NOT_FOUND",
  "CONTRACT_READ_FAILED",
  "YAML_PARSE_FAILED",
  "YAML_DUPLICATE_KEY",
  "YAML_NESTING_TOO_DEEP",
  "CONTRACT_SCHEMA_INVALID",
  "CONTRACT_VERSION_UNSUPPORTED",
  "COMMAND_IDENTIFIER_INVALID",
  "COMMAND_REFERENCE_INVALID",
  "COMMAND_DUPLICATE",
  "RUNTIME_DECLARATION_INVALID",
  "PACKAGE_MANAGER_INVALID",
  "PATH_PATTERN_INVALID",
  "PATH_ABSOLUTE_DISALLOWED",
  "PATH_TRAVERSAL_DISALLOWED",
  "PATH_CATEGORY_CONFLICT",
  "INSTRUCTION_SOURCE_INVALID",
  "ARCHITECTURE_DECISION_INVALID",
  "AGENT_CONTEXT_FILE_INVALID",
  "ADAPTER_DECLARATION_INVALID",
  "NORMALIZATION_FAILED",
  "INTERNAL_INVARIANT_VIOLATION",
  "GENERATE_TARGET_UNMANAGED",
  "GENERATE_WRITE_FAILED",
  "GENERATED_FILES_OUT_OF_DATE",
  "GENERATE_OUTSIDE_REPO_ROOT",
  "ADAPTER_NOT_YET_IMPLEMENTED",
  "PROTECTED_PATH_MODIFIED",
  "GIT_UNAVAILABLE",
  "GIT_REPOSITORY_NOT_FOUND",
  "VERIFICATION_NOT_DECLARED",
  "VERIFICATION_COMMAND_FAILED",
  "VERIFICATION_COMMAND_TIMEOUT",
  "VERIFICATION_COMMAND_SPAWN_FAILED",
  "VERIFICATION_RECORD_WRITE_FAILED",
  "HANDOFF_FILE_INVALID",
  "HANDOFF_FIELD_TOO_LONG",
  "DOCUMENTATION_SOURCE_READ_FAILED",
  "DOCUMENTATION_LINK_CHECK_FAILED",
  "DOCUMENTATION_LINK_BROKEN",
  "DOCUMENTATION_LINK_OUTSIDE_REPOSITORY",
  "INSTRUCTION_SOURCE_TOO_LARGE",
  "RUNTIME_VERSION_MISMATCH",
  "RUN_DECLARED_BUT_DOCTOR_UNSUPPORTED",
  "PACKAGE_MANAGER_UNAVAILABLE",
  "PACKAGE_MANAGER_VERSION_MISMATCH",
  "GIT_REQUIRED_BUT_UNAVAILABLE",
  "INIT_CONTRACT_EXISTS",
  "UPGRADE_NO_CHANGES_NEEDED",
  "UPGRADE_MANUAL_REVIEW_REQUIRED",
  "UPGRADE_WRITE_FAILED",
] as const;

export type DiagnosticCode = (typeof DIAGNOSTIC_CODES)[number];

export function isDiagnosticCode(value: string): value is DiagnosticCode {
  return (DIAGNOSTIC_CODES as readonly string[]).includes(value);
}
