/**
 * Machine-checkable banner embedded at the top of every file Agent-Ready
 * generates. Its presence is what lets `generate --write` tell a
 * previously generated file apart from one a human wrote by hand, so a
 * re-run never silently clobbers hand-authored content (see ADR-0010).
 */
export const GENERATED_FILE_MARKER =
  "<!-- Generated by agent-ready from agent-ready.yaml. Do not edit directly. -->";

/**
 * Returns true if `content` was produced by Agent-Ready (contains the
 * managed-file marker), false otherwise — including for empty content or
 * content that merely resembles the marker but doesn't match it exactly.
 */
export function hasManagedMarker(content: string): boolean {
  return content.includes(GENERATED_FILE_MARKER);
}
