import { loadContract } from "../../contract/pipeline.js";
import { renderDiagnosticsHuman } from "../../diagnostics/humanRender.js";
import { renderDiagnosticsJson } from "../../diagnostics/jsonRender.js";
import { ExitCode, resolveExitCode } from "../../diagnostics/exitCodes.js";
import type { Diagnostic } from "../../diagnostics/types.js";
import { FileSystemError } from "../../filesystem/types.js";
import type { FileSystem } from "../../filesystem/types.js";
import { planGeneration, resolvePlannedOutputs } from "../../generate/generate.js";
import { checkGeneratedFiles } from "../../generate/check.js";
import type { PlannedOutputStatus } from "../../generate/types.js";
import type { CliOutcome } from "./validate.js";

export interface GenerateArgs {
  readonly json: boolean;
  readonly config?: string;
  readonly write: boolean;
  readonly check: boolean;
  readonly force: boolean;
}

type GenerateMode = "dry-run" | "write" | "check";
type FileStatus = PlannedOutputStatus | "written" | "refused";

interface GenerateFileReport {
  readonly adapter: string;
  readonly relativePath: string;
  readonly absolutePath: string;
  readonly status: FileStatus;
}

/**
 * Plans and (optionally) writes the enabled adapters' output
 * (AGENTS.md, CLAUDE.md, .cursorrules, .github/copilot-instructions.md,
 * GEMINI.md) from the validated contract. Defaults to a dry run —
 * nothing is written unless `--write` is passed. Never executes
 * repository commands.
 */
export async function runGenerate(
  fs: FileSystem,
  args: GenerateArgs,
  startDir?: string,
): Promise<CliOutcome> {
  if (args.check && args.write) {
    const message = "--check and --write cannot be used together.";
    if (args.json) {
      const body = { ok: false, error: message };
      return {
        exitCode: ExitCode.VALIDATION_FAILED,
        stdout: JSON.stringify(body, null, 2) + "\n",
        stderr: "",
      };
    }
    return {
      exitCode: ExitCode.VALIDATION_FAILED,
      stdout: "",
      stderr: `agent-ready generate: ${message}\n`,
    };
  }
  const mode: GenerateMode = args.check ? "check" : args.write ? "write" : "dry-run";

  const result = await loadContract({
    fs,
    startDir,
    ...(args.config !== undefined && { explicitConfigPath: args.config }),
  });

  if (!result.ok) {
    const exitCode = resolveExitCode(result.diagnostics);
    if (args.json) {
      const body = { ok: false, diagnostics: renderDiagnosticsJson(result.diagnostics) };
      return { exitCode, stdout: JSON.stringify(body, null, 2) + "\n", stderr: "" };
    }
    return { exitCode, stdout: "", stderr: renderDiagnosticsHuman(result.diagnostics) + "\n" };
  }

  const { contract, repoRoot, contractPath } = result.value;
  const plan = planGeneration(contract, repoRoot);
  const checked = mode === "check" ? await checkGeneratedFiles(fs, contract, repoRoot) : undefined;
  const planned = checked?.files ?? (await resolvePlannedOutputs(fs, plan.entries));

  const diagnostics: Diagnostic[] = [
    ...result.diagnostics,
    ...(checked?.diagnostics ?? plan.diagnostics),
  ];
  const reports: GenerateFileReport[] = [];
  let checkDrift = false;

  for (const output of planned) {
    if (mode === "dry-run") {
      reports.push(toReport(output, output.status));
      continue;
    }

    if (mode === "check") {
      if (output.status !== "up-to-date") {
        checkDrift = true;
      }
      reports.push(toReport(output, output.status));
      continue;
    }

    // mode === "write"
    if (output.status === "up-to-date") {
      reports.push(toReport(output, "up-to-date"));
      continue;
    }

    if (output.status === "unmanaged" && !args.force) {
      diagnostics.push({
        code: "GENERATE_TARGET_UNMANAGED",
        severity: "error",
        summary: `${output.relativePath} already exists and was not generated by Agent-Ready.`,
        detail: "Refusing to overwrite a file that lacks the managed-file marker.",
        sourcePath: output.relativePath,
        remediation: "Remove or rename the existing file, or re-run with --force.",
      });
      reports.push(toReport(output, "refused"));
      continue;
    }

    try {
      await fs.writeTextFile(output.absolutePath, output.content);
      reports.push(toReport(output, "written"));
    } catch (error) {
      diagnostics.push({
        code: "GENERATE_WRITE_FAILED",
        severity: "error",
        summary: `Failed to write ${output.relativePath}.`,
        detail: error instanceof FileSystemError ? error.message : "Unknown write error.",
        sourcePath: output.relativePath,
        remediation: "Check file permissions and available disk space.",
      });
      reports.push(toReport(output, "refused"));
    }
  }

  let exitCode = resolveExitCode(diagnostics);
  if (mode === "check" && checkDrift && exitCode === ExitCode.SUCCESS) {
    exitCode = ExitCode.VALIDATION_FAILED;
  }

  if (args.json) {
    const body = {
      ok: exitCode === ExitCode.SUCCESS,
      contractPath,
      repoRoot,
      mode,
      files: reports.map((report) => ({
        adapter: report.adapter,
        path: report.absolutePath,
        relativePath: report.relativePath,
        status: report.status,
      })),
      diagnostics: renderDiagnosticsJson(diagnostics),
    };
    return { exitCode, stdout: JSON.stringify(body, null, 2) + "\n", stderr: "" };
  }

  const lines = [`Generate (${mode}) - repoRoot: ${repoRoot}`, ""];
  if (reports.length === 0) {
    lines.push("  (no adapters enabled)");
  }
  for (const report of reports) {
    lines.push(`  ${report.relativePath} [${report.adapter}]: ${report.status}`);
  }
  if (diagnostics.length > 0) {
    lines.push("", renderDiagnosticsHuman(diagnostics));
  }
  return { exitCode, stdout: lines.join("\n") + "\n", stderr: "" };
}

function toReport(
  output: { adapter: string; relativePath: string; absolutePath: string },
  status: FileStatus,
): GenerateFileReport {
  return {
    adapter: output.adapter,
    relativePath: output.relativePath,
    absolutePath: output.absolutePath,
    status,
  };
}
