import { describe, expect, it } from "vitest";
import { runInit } from "../../src/cli/commands/init.js";
import { InMemoryFileSystem } from "../../src/filesystem/inMemoryFileSystem.js";
import { ExitCode } from "../../src/diagnostics/exitCodes.js";

function fs(): InMemoryFileSystem {
  const f = new InMemoryFileSystem("/repo");
  // .git directory so discoverRepoRoot finds the repo root
  f.addDirectory("/repo/.git");
  return f;
}

// ── Dry-run ────────────────────────────────────────────────────────────────

describe("runInit — dry run", () => {
  it("prints detection summary and proposed YAML to stdout", async () => {
    const fsys = fs();
    fsys.addFile(
      "/repo/package.json",
      JSON.stringify({
        name: "my-project",
        description: "A test project.",
        scripts: {
          lint: "eslint .",
          test: "vitest",
          build: "tsc",
        },
      }),
    );
    const outcome = await runInit(fsys, { json: false, write: false });
    expect(outcome.exitCode).toBe(ExitCode.SUCCESS);
    expect(outcome.stdout).toContain("agent-ready init - repoRoot:");
    expect(outcome.stdout).toContain("project name: my-project");
    expect(outcome.stdout).toContain("--- proposed agent-ready.yaml");
    expect(outcome.stdout).toContain("version: 1");
    expect(outcome.stdout).toContain("name: my-project");
    expect(outcome.stdout).toContain("description: A test project.");
    expect(outcome.stdout).toContain("lint:");
    expect(outcome.stdout).toContain("run: eslint .");
    expect(outcome.stdout).toContain("Validation: would pass");
    expect(outcome.stdout).toContain("agent-ready init --write");
    expect(outcome.stderr).toBe("");
  });

  it("exits 0 even when generated contract is minimal (no scripts, no env)", async () => {
    const fsys = fs();
    // A minimal package.json with just a name — no scripts, no engines, no
    // packageManager. The generated contract should still pass validation.
    fsys.addFile("/repo/package.json", JSON.stringify({ name: "minimal" }));
    const outcome = await runInit(fsys, { json: false, write: false });
    expect(outcome.exitCode).toBe(ExitCode.SUCCESS);
    expect(outcome.stdout).toContain("Validation: would pass");
  });

  it("includes skipped scripts in detection summary", async () => {
    const fsys = fs();
    fsys.addFile(
      "/repo/package.json",
      JSON.stringify({
        name: "test",
        scripts: {
          lint: "eslint .",
          dev: "vite",
          start: "node dist/index.js",
        },
      }),
    );
    const outcome = await runInit(fsys, { json: false, write: false });
    expect(outcome.stdout).toContain("dev, start");
    expect(outcome.stdout).toContain("1 included");
    expect(outcome.stdout).toContain("2 skipped");
  });

  it("includes detection-source comments in generated YAML", async () => {
    const fsys = fs();
    fsys.addFile(
      "/repo/package.json",
      JSON.stringify({
        name: "my-project",
        engines: { node: ">=20" },
        packageManager: "pnpm@10.0.0",
        scripts: { lint: "eslint .", test: "vitest" },
      }),
    );
    fsys.addFile("/repo/.gitignore", "node_modules/\n.env\ndist/\n");
    const outcome = await runInit(fsys, { json: false, write: false });
    const yamlPart = outcome.stdout.substring(
      outcome.stdout.indexOf("--- proposed"),
      outcome.stdout.lastIndexOf("---") + 3,
    );
    expect(yamlPart).toContain("# Generated by agent-ready init");
    expect(yamlPart).toContain("project.name: from package.json");
    expect(yamlPart).toContain("environment.runtimes.node: from engines.node");
    expect(yamlPart).toContain("environment.packageManager: from package.json");
    expect(yamlPart).toContain("paths.ignored: from .gitignore");
    expect(yamlPart).toContain("paths.protected: .env* in .gitignore");
  });

  it("works for a minimal repo with no package.json", async () => {
    const fsys = new InMemoryFileSystem("/my-repo");
    fsys.addDirectory("/my-repo/.git");
    const outcome = await runInit(fsys, { json: false, write: false });
    expect(outcome.exitCode).toBe(ExitCode.SUCCESS);
    expect(outcome.stdout).toContain("project name: my-repo (from directory)");
    expect(outcome.stdout).toContain("version: 1");
    expect(outcome.stdout).toContain("name: my-repo");
  });

  it("emits all five adapters enabled by default", async () => {
    const fsys = fs();
    fsys.addFile("/repo/package.json", JSON.stringify({ name: "test" }));
    const outcome = await runInit(fsys, { json: false, write: false });
    const yamlPart = outcome.stdout.substring(outcome.stdout.indexOf("--- proposed"));
    expect(yamlPart).toContain("agentsMd:\n    enabled: true");
    expect(yamlPart).toContain("claude:\n    enabled: true");
    expect(yamlPart).toContain("cursor:\n    enabled: true");
    expect(yamlPart).toContain("copilot:\n    enabled: true");
    expect(yamlPart).toContain("gemini:\n    enabled: true");
  });
});

// ── JSON output ────────────────────────────────────────────────────────────

describe("runInit — JSON output", () => {
  it("emits structured JSON for dry run", async () => {
    const fsys = fs();
    fsys.addFile(
      "/repo/package.json",
      JSON.stringify({
        name: "test",
        scripts: { lint: "eslint .", test: "vitest" },
      }),
    );
    const outcome = await runInit(fsys, { json: true, write: false });
    expect(outcome.exitCode).toBe(ExitCode.SUCCESS);
    const body = JSON.parse(outcome.stdout) as Record<string, unknown>;
    expect(body["ok"]).toBe(true);
    expect(typeof body["repoRoot"]).toBe("string");
    expect(body["mode"]).toBe("dry-run");
    const detection = body["detection"] as Record<string, unknown>;
    expect(detection["projectName"]).toBe("test");
    expect(detection["projectNameSource"]).toBe("package.json");
    expect(Array.isArray(detection["scriptsIncluded"])).toBe(true);
    const scripts = detection["scriptsIncluded"] as string[];
    expect(scripts).toContain("lint");
    expect(scripts).toContain("test");
    expect(typeof body["contract"]).toBe("string");
    expect(body["validationPassed"]).toBe(true);
    expect(body["diagnostics"]).toEqual([]);
  });

  it("includes all expected top-level keys in JSON dry-run output", async () => {
    const fsys = fs();
    fsys.addFile("/repo/package.json", JSON.stringify({ name: "test" }));
    const outcome = await runInit(fsys, { json: true, write: false });
    const body = JSON.parse(outcome.stdout) as Record<string, unknown>;
    expect(Object.keys(body).sort()).toEqual([
      "contract",
      "detection",
      "diagnostics",
      "mode",
      "ok",
      "repoRoot",
      "validationPassed",
    ]);
  });

  it("includes detection metadata in JSON", async () => {
    const fsys = fs();
    fsys.addFile(
      "/repo/package.json",
      JSON.stringify({
        name: "test",
        packageManager: "pnpm@10.0.0",
        engines: { node: ">=20" },
      }),
    );
    const outcome = await runInit(fsys, { json: true, write: false });
    const body = JSON.parse(outcome.stdout) as Record<string, unknown>;
    const detection = body["detection"] as Record<string, unknown>;
    expect(detection["projectNameSanitized"]).toBe(false);
    expect(detection["nodeRange"]).toBe(">=20");
    expect(detection["nodeRangeSource"]).toBe("engines.node");
    expect(detection["packageManager"]).toEqual({ name: "pnpm", version: "10.0.0" });
    expect(detection["packageManagerSource"]).toBe("package.json");
  });
});

// ── --write ─────────────────────────────────────────────────────────────────

describe("runInit — write", () => {
  it("writes agent-ready.yaml and reports success", async () => {
    const fsys = fs();
    fsys.addFile(
      "/repo/package.json",
      JSON.stringify({
        name: "my-project",
        scripts: { lint: "eslint ." },
      }),
    );
    const outcome = await runInit(fsys, { json: false, write: true });
    expect(outcome.exitCode).toBe(ExitCode.SUCCESS);
    expect(outcome.stdout).toContain("Wrote agent-ready.yaml");
    expect(outcome.stdout).toContain("Next steps:");
    expect(outcome.stdout).toContain("agent-ready validate");

    // Verify the file was actually written.
    const written = await fsys.readTextFile("/repo/agent-ready.yaml");
    expect(written).toContain("version: 1");
    expect(written).toContain("name: my-project");
  });

  it("JSON output for write reports expected keys", async () => {
    const fsys = fs();
    fsys.addFile(
      "/repo/package.json",
      JSON.stringify({ name: "my-project" }),
    );
    const outcome = await runInit(fsys, { json: true, write: true });
    expect(outcome.exitCode).toBe(ExitCode.SUCCESS);
    const body = JSON.parse(outcome.stdout) as Record<string, unknown>;
    expect(body["ok"]).toBe(true);
    expect(body["mode"]).toBe("write");
    expect(body["validationPassed"]).toBe(true);
    expect(body["contractPath"]).toBe("/repo/agent-ready.yaml");
    expect(body["detection"]).toBeDefined();
  });

  it("refuses to write when agent-ready.yaml already exists", async () => {
    const fsys = fs();
    fsys.addFile("/repo/package.json", JSON.stringify({ name: "test" }));
    fsys.addFile("/repo/agent-ready.yaml", "version: 1\nproject:\n  name: existing\n");
    const outcome = await runInit(fsys, { json: false, write: true });
    expect(outcome.exitCode).toBe(ExitCode.VALIDATION_FAILED);
    expect(outcome.stderr).toContain("already exists");
    expect(outcome.stderr).toContain("Remove or rename the existing agent-ready.yaml");
    // Verify the existing file was not modified.
    const existing = await fsys.readTextFile("/repo/agent-ready.yaml");
    expect(existing).toContain("name: existing");
  });

  it("refuses to write dry-run when agent-ready.yaml exists", async () => {
    const fsys = fs();
    fsys.addFile("/repo/package.json", JSON.stringify({ name: "test" }));
    fsys.addFile("/repo/agent-ready.yaml", "version: 1\nproject:\n  name: existing\n");
    const outcome = await runInit(fsys, { json: false, write: false });
    expect(outcome.exitCode).toBe(ExitCode.VALIDATION_FAILED);
    expect(outcome.stderr).toContain("already exists");
  });

  it("JSON dry-run contract-exists case has expected shape", async () => {
    const fsys = fs();
    fsys.addFile("/repo/package.json", JSON.stringify({ name: "test" }));
    fsys.addFile("/repo/agent-ready.yaml", "version: 1\nproject:\n  name: existing\n");
    const outcome = await runInit(fsys, { json: true, write: false });
    expect(outcome.exitCode).toBe(ExitCode.VALIDATION_FAILED);
    const body = JSON.parse(outcome.stdout) as Record<string, unknown>;
    expect(body["ok"]).toBe(false);
    expect(body["mode"]).toBe("dry-run");
    expect(body["repoRoot"]).toBe("/repo");
    expect(body["contractPath"]).toBe("/repo/agent-ready.yaml");
    const diags = body["diagnostics"] as { code: string }[];
    expect(diags[0]?.["code"]).toBe("INIT_CONTRACT_EXISTS");
  });

  it("JSON output for contract-exists case has expected shape", async () => {
    const fsys = fs();
    fsys.addFile("/repo/package.json", JSON.stringify({ name: "test" }));
    fsys.addFile("/repo/agent-ready.yaml", "version: 1\nproject:\n  name: existing\n");
    const outcome = await runInit(fsys, { json: true, write: true });
    expect(outcome.exitCode).toBe(ExitCode.VALIDATION_FAILED);
    const body = JSON.parse(outcome.stdout) as Record<string, unknown>;
    expect(body["ok"]).toBe(false);
    expect(body["mode"]).toBe("write");
    expect(body["repoRoot"]).toBe("/repo");
    expect(body["contractPath"]).toBe("/repo/agent-ready.yaml");
    const diags = body["diagnostics"] as { code: string }[];
    expect(diags[0]?.code).toBe("INIT_CONTRACT_EXISTS");
  });
});

// ── Verification scripts ───────────────────────────────────────────────────

describe("runInit — verification scripts ordering", () => {
  it("preserves package.json script order in verification.required", async () => {
    const fsys = fs();
    fsys.addFile(
      "/repo/package.json",
      JSON.stringify({
        name: "test",
        scripts: {
          build: "tsc",
          test: "vitest",
          lint: "eslint .",
          typecheck: "tsc --noEmit",
        },
      }),
    );
    const outcome = await runInit(fsys, { json: false, write: false });
    const yamlPart = outcome.stdout.substring(outcome.stdout.indexOf("--- proposed"));
    // Verification lines should appear in the order they were in package.json.
    // Find the verification section and check order.
    const beforeVerification = yamlPart.indexOf("verification:");
    const afterVerification = yamlPart.indexOf("adapters:", beforeVerification);
    const verificationSection = yamlPart.substring(
      beforeVerification,
      afterVerification > 0 ? afterVerification : undefined,
    );
    const buildIdx = verificationSection.indexOf("- build");
    const testIdx = verificationSection.indexOf("- test");
    const lintIdx = verificationSection.indexOf("- lint");
    const typecheckIdx = verificationSection.indexOf("- typecheck");
    expect(buildIdx).toBeGreaterThan(-1);
    expect(testIdx).toBeGreaterThan(-1);
    expect(lintIdx).toBeGreaterThan(-1);
    expect(typecheckIdx).toBeGreaterThan(-1);
    expect(buildIdx).toBeLessThan(testIdx);
    expect(testIdx).toBeLessThan(lintIdx);
    expect(lintIdx).toBeLessThan(typecheckIdx);
  });
});

// ── YAML string quoting ─────────────────────────────────────────────────────

describe("runInit — YAML quoting", () => {
  it("quotes project descriptions containing colons", async () => {
    const fsys = fs();
    fsys.addFile(
      "/repo/package.json",
      JSON.stringify({
        name: "test",
        description: "A project: with a colon",
      }),
    );
    const outcome = await runInit(fsys, { json: false, write: false });
    expect(outcome.stdout).toContain('description: "A project: with a colon"');
  });

  it("does not quote simple project names", async () => {
    const fsys = fs();
    fsys.addFile("/repo/package.json", JSON.stringify({ name: "simple-name" }));
    const outcome = await runInit(fsys, { json: false, write: false });
    // The name may appear in multiple contexts; verify it's in the contract body unquoted.
    expect(outcome.stdout).toContain("name: simple-name");
    // The unquoted appearance in the YAML body (not detection summary).
  });
});

// ── Enrichment: hint files and lock files ──────────────────────────────────

describe("runInit — enrichment", () => {
  it("detects Node range from .nvmrc when engines.node is absent", async () => {
    const fsys = fs();
    fsys.addFile("/repo/package.json", JSON.stringify({ name: "test" }));
    fsys.addFile("/repo/.nvmrc", "20");
    const outcome = await runInit(fsys, { json: false, write: false });
    expect(outcome.stdout).toContain(">=20 <21");
  });

  it("detects package manager from lock file when packageManager field is absent", async () => {
    const fsys = fs();
    fsys.addFile("/repo/package.json", JSON.stringify({ name: "test" }));
    fsys.addFile("/repo/pnpm-lock.yaml", "");
    const outcome = await runInit(fsys, { json: false, write: false });
    expect(outcome.stdout).toContain("packageManager:");
    expect(outcome.stdout).toContain("name: pnpm");
  });

  it("prefers engines.node over .nvmrc when both are present", async () => {
    const fsys = fs();
    fsys.addFile(
      "/repo/package.json",
      JSON.stringify({ name: "test", engines: { node: ">=22" } }),
    );
    fsys.addFile("/repo/.nvmrc", "20");
    const outcome = await runInit(fsys, { json: false, write: false });
    expect(outcome.stdout).toContain('node: ">=22"');
    expect(outcome.stdout).not.toContain(">=20 <21");
  });
});
