import { describe, expect, it } from "vitest";
import { GENERATED_FILE_MARKER, hasManagedMarker } from "../../src/generate/marker.js";

describe("hasManagedMarker", () => {
  it("returns true when the marker is present", () => {
    expect(hasManagedMarker(`${GENERATED_FILE_MARKER}\n\n# AGENTS.md\n`)).toBe(true);
  });

  it("returns false for empty content", () => {
    expect(hasManagedMarker("")).toBe(false);
  });

  it("returns false for hand-authored content without the marker", () => {
    expect(hasManagedMarker("# My hand-written AGENTS.md\n")).toBe(false);
  });

  it("returns false for content that merely resembles the marker", () => {
    expect(hasManagedMarker("<!-- Generated by some other tool -->")).toBe(false);
  });
});
